name: Test Flask App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-flask:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Flask app in background
      run: |
        export FLASK_APP=app.py
        flask run --port=5001 &
        sleep 5  # wait for server to start

    - name: Call PDF generation route
      run: |
        curl -X POST http://127.0.0.1:5001/generate_pdf \
          -H "Content-Type: application/json" \
          -d '{"ticket_number": "123456", "meter_number": "A123", "date": "2025-08-01", "time": "10:00"}'

    - name: Check if PDF was generated
      run: |
        ls -lh
        file output.pdf | grep -q "PDF document" \
        && echo "✅ PDF was successfully generated." \
        || (echo "❌ PDF not generated!" && exit 1)      - name: Check if PDF was generated
        run: |
          file output.pdf | grep -q "PDF document" && echo "✅ PDF generated" || (echo "❌ Not a PDF" && exit 1)
